"""add norad_id to satellites

Revision ID: 5090090fc03d
Revises: 779062f0e641
Create Date: 2026-05-04 20:37:50.609606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5090090fc03d'
down_revision: Union[str, Sequence[str], None] = '779062f0e641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('satellites', sa.Column('norad_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('satellites', 'norad_id')
    # ### end Alembic commands ###
